# Trong file _config.yml

title: Nửa Bước Thành Thơ
description: Sao Thủy là vì sao gần Mặt Trời nhất...
theme: jekyll-theme-minimal
markdown: kramdown
permalink: /:year/:month/:day/:title.html

# THÊM DÒNG NÀY, RẤT QUAN TRỌNG
url: "https://nuabuocthanhtho.github.io"

# Cấu hình excerpt (đoạn trích)
excerpt_separator: ""
collections:
  stories:
    output: true

# Cấu hình phân trang (Pagination)
paginate: 10
paginate_path: "/page/:num/"

# Cấu hình plugin
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  # <-- SỬA TÊN PLUGIN CHO ĐÚNG
